return {
    title1 = "Smart",
    title2 = "Bingo",
    pass = "PASS(%d-%d)",
    rule = "Rules",
    check = "Check",
    rules = {
        "Red: ≥1 tick around",
        "Blue: ≤2 ticks around",
        "Black: must be ticked",
        "Green: same tick count on ROW and COLUMN",
        "Yellow: same tick count on DIAGONAL",
        "Orange: EVEN num of ticks around",
        "Purple: ODD num of ticks around",
        "Pink: tick on this color must be ISOLATE",
        "Cyan: tick on this color must NON-ISOLATE",
    },
    target = "Have five Ticks in a line to prove you are not an idiot",
    winDaily = "Daily puzzle solved!\nYou are not an idiot!",
    winAny = "Puzzle solved!",
    winMax = "New maximal ticks!",
    winMin = "New minimal ticks!",
    easyMode = "NORMAL MODE",
    hardMode = "HARD MODE",
    credits = "Made By 26F Studio    Idea from QQ group image",
    sound = "Sound",
    language = "文/A",
}
